name = input("Ввидите своё имя: ")
familia = input("Видите свою фамилию: ")
age = input("Ввидите свой возраст: ")
town = input("Ввидите место проживания: ")
print(f"Меня зовут {name} {familia}. Город Проживания - {town}. Возраст {age}.")
